### ISSUE TITLE
Regarding delegation of environments

### ISSUE THREAD

**Issue by Chlorie** [brycelelbach/wg21_p2300_execution#32] opened 2023-02-16 13:15 UTC
11.7.5.1. General [exec.adapt.general] currently states:
> - Unless otherwise specified, all sender adaptors that accept a single `sender` argument return sender objects that delegate `get_env` to that single sender argument.
> - Unless otherwise specified, whenever a sender adaptor constructs a receiver that it passes to another sender’s connect, that receiver shall delegate `get_env` to a receiver accepted as an argument of `execution::connect`.

This delegation of the environment causes all the queries to be forwarded, regardless of whether the said query is a *`forwarding-query`*. Is this intentional?

**Comment by ericniebler** [comment] 2023-02-16 15:29
It's a bug, thanks.

**Comment by ericniebler** [comment] 2023-02-16 15:31
Dupe of #21

**Closed by ericniebler** 2023-02-16 15:31 UTC
Labels: bug
